PRAGMA encoding = "UTF-8";
PRAGMA foreign_keys = ON;

CREATE TABLE ANIMATURE (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	"name" TEXT NOT NULL,
	"height" INTEGER NOT NULL,
	"weight" INTEGER NOT NULL,
	"type" INTEGER NOT NULL,
	"type2" INTEGER, 
	"description" TEXT NOT NULL,
	"speed" INTEGER NOT NULL,
	"defense" INTEGER NOT NULL,
	"agility" INTEGER NOT NULL,
	"strenght" INTEGER NOT NULL,
	"precission" INTEGER NOT NULL,
	"health" INTEGER NOT NULL,
	"level_evo" INTEGER, 
	"baseExp" INTEGER  NOT NULL
	"captureRange" NUMBER NOT NULL);

CREATE TABLE ATTACK (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	"name" TEXT  NOT NULL, 
	"type" INTEGER NOT NULL,
	"max_pp" INTEGER NOT NULL,
	"active" INTEGER NOT NULL,
	"ifPass" INTEGER,
	"power" INTEGER NOT NULL,
	"probability" INTEGER NOT NULL);

CREATE TABLE CAPTURED (
	"id_Captured" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"id_Animature" INTEGER NOT NULL,
	"save" INTEGER NOT NULL,
	"nickname" TEXT, 
	"sex" INTEGER NOT NULL,
	"status" INTEGER NOT NULL,
	"capturedTime" INTEGER, 
	"attack1" INTEGER, 
	"attack1_pp" INTEGER, 
	"attack2" INTEGER, 
	"attack2_pp" INTEGER, 
	"attack3" INTEGER, 
	"attack3_pp" INTEGER, 
	"attack4" INTEGER, 
	"attack4_pp" INTEGER, 
	"health" INTEGER NOT NULL,
	"level" INTEGER NOT NULL,
	"cur_exp" INTEGER NOT NULL,
	"exp" INTEGER NOT NULL,
	"box" INTEGER, 
	FOREIGN KEY(id_Animature) REFERENCES ANIMATURE(id) ON DELETE CASCADE, 
	FOREIGN KEY(save) REFERENCES SAVE(id) ON DELETE CASCADE, 
	FOREIGN KEY(attack1) REFERENCES ATTACK(id) ON DELETE CASCADE, 
	FOREIGN KEY(attack2) REFERENCES ATTACK(id) ON DELETE CASCADE, 
	FOREIGN KEY(attack3) REFERENCES ATTACK(id) ON DELETE CASCADE, 
	FOREIGN KEY(attack4) REFERENCES ATTACK(id) ON DELETE CASCADE);

CREATE TABLE ITEM (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"name" TEXT NOT NULL,
	"type" NUMBER NOT NULL,
	"description" TEXT NOT NULL);

CREATE TABLE ENEMY (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"map" INTEGER NOT NULL,
	"coord_x" INTEGER NOT NULL,
	"coord_y" INTEGER NOT NULL,
	"money" INTEGER NOT NULL,
	"an1" INTEGER NOT NULL,
	"an2" INTEGER, 
	"an3" INTEGER, 
	"an4" INTEGER, 
	"an5" INTEGER, 
	"an6" INTEGER, 
	FOREIGN KEY(an1) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an2) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an3) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an4) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an5) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an6) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE);

CREATE TABLE SAVE (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"character" INTEGER NOT NULL,
	"stage" INTEGER NOT NULL,
	"last_played" DATE, 
	"started" DATE, 
	"total_time" INTEGER, 
	"steps" INTEGER, 
	"an1" INTEGER NOT NULL,
	"an2" INTEGER, 
	"an3" INTEGER, 
	"an4" INTEGER, 
	"an5" INTEGER, 
	"an6" INTEGER, 
	"map" INTEGER, 
	"coord_x" INTEGER NOT NULL,
	"coord_y" INTEGER NOT NULL,
	"neighbour" INTEGER NOT NULL,
	"first_an" INTEGER NOT NULL,
	"orientation" INTEGER NOT NULL,
	"last_HealingMap" INTEGER NOT NULL,
	"last_HealingX" INTEGER NOT NULL,
	"last_HealingY" INTEGER NOT NULL,
	"medals" INTEGER NOT NULL,
	"money" INTEGER NOT NULL, 
	FOREIGN KEY(an1) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an2) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an3) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an4) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an5) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(an6) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE, 
	FOREIGN KEY(first_an) REFERENCES CAPTURED(id_Captured) ON DELETE CASCADE);

CREATE TABLE USER (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"email" TEXT NOT NULL,
	"password" TEXT NOT NULL,
	"username" TEXT NOT NULL,
	"is_current" INTEGER NOT NULL,
	"save" INTEGER NOT NULL,
	FOREIGN KEY(save) REFERENCES SAVE(id) ON DELETE CASCADE);


CREATE TABLE BAG (
	"save" NUMBER NOT NULL,
	"item" NUMBER NOT NULL,
	"quantity" NUMBER NOT NULL,
	FOREIGN KEY(save) REFERENCES SAVE(id) ON DELETE CASCADE, 
	FOREIGN KEY(item) REFERENCES ITEM(id) ON DELETE CASCADE,
	PRIMARY KEY (save, item));

CREATE TABLE VIEWEDANIMATURE (
	"id_Save" INTEGER REFERENCES SAVE(id),
	"id_Animature" INTEGER REFERENCES ANIMATURE(id),
	PRIMARY KEY (id_Save, id_Animature));

CREATE TABLE ANIMATUREATTACK (
	"id_Animature" INTEGER REFERENCES ANIMATURE(id),
	"id_Attack" INTEGER REFERENCES ATTACK(id),
	"level" INTEGER, 
	PRIMARY KEY (id_Animature, id_Attack));

CREATE TABLE FIGHTS (
	"save" INTEGER PRIMARY KEY NULL, 
	"enemy" INTEGER NOT NULL, 
	FOREIGN KEY(save) REFERENCES SAVE(id) ON DELETE CASCADE, 
	FOREIGN KEY(enemy) REFERENCES ENEMY(id) ON DELETE CASCADE);

INSERT INTO ANIMATURE VALUES (1, 'BULBASUR', 0.7, 6.9, 3, 7, 100, 120, 100, 120, 100, 80, 16, 150);
INSERT INTO ANIMATURE VALUES (2, 'IVYSAUR', 1, 13, 3, 7, 100, 120, 100, 120, 100, 80, 36, 500);
INSERT INTO ANIMATURE VALUES (3, 'VENUSAUR', 2, 100, 3, 7, 100, 120, 100, 120, 100, 80, -1, 1200);

INSERT INTO ANIMATURE VALUES (4, 'CHARMANDER', 0.6, 8.5, 1, -1, 100, 120, 100, 120, 100, 80, 16, 150);
INSERT INTO ANIMATURE VALUES (5, 'CHARMELEON', 1.1, 19, 1, -1, 100, 120, 100, 120, 100, 80, 36, 500);
INSERT INTO ANIMATURE VALUES (6, 'CHARIZARD', 1.7, 90.5, 1, 9, 100, 120, 100, 120, 100, 80, -1, 1200);

INSERT INTO ANIMATURE VALUES (7, 'SQUIRTLE', 0.5, 9, 2, -1, 100, 120, 100, 120, 100, 80, 16, 150);
INSERT INTO ANIMATURE VALUES (8, 'WARTORTLE', 1, 22.5, 2, -1, 100, 120, 100, 120, 100, 80, 36, 500);
INSERT INTO ANIMATURE VALUES (9, 'BLASTOISE', 1.6, 85.5, 2, -1, 100, 120, 100, 120, 100, 80, -1, 1200);

INSERT INTO ANIMATURE VALUES (10, 'CATERPIE', 0.3, 2.9, 11, -1, 100, 120, 100, 120, 100, 80, 8, 150);
INSERT INTO ANIMATURE VALUES (11, 'METAPOD', 0.7, 9.9, 11, -1, 100, 120, 100, 120, 100, 80, 18, 500);
INSERT INTO ANIMATURE VALUES (12, 'BUTTERFREE', 1.1, 32, 11, 9, 100, 120, 100, 120, 100, 80, -1, 1200);

INSERT INTO ANIMATURE VALUES (13, 'WEEDLE', 0.3, 3.2, 11, 7, 100, 120, 100, 120, 100, 80, 8, 150);
INSERT INTO ANIMATURE VALUES (14, 'KAKUNA', 0.6, 10, 11, 7, 100, 120, 100, 120, 100, 80, 18, 500);
INSERT INTO ANIMATURE VALUES (15, 'BEEDRILL', 1, 29.5, 11, 7, 100, 120, 100, 120, 100, 80, -1, 1200);

INSERT INTO ANIMATURE VALUES (16, 'PIDGEY', 0.3, 3.2, 0, 9, 100, 120, 100, 120, 100, 80, 16, 150);
INSERT INTO ANIMATURE VALUES (17, 'PIDGEOTTO', 0.6, 10, 0, 9, 100, 120, 100, 120, 100, 80, 36, 500);
INSERT INTO ANIMATURE VALUES (18, 'PIDGEOT', 1, 29.5, 0, 9, 100, 120, 100, 120, 100, 80, -1, 1200);

INSERT INTO ANIMATURE VALUES (19, 'RATTATA', 0.3, 3.5, 0, -1, 100, 120, 100, 120, 100, 80, 12, 150);
INSERT INTO ANIMATURE VALUES (20, 'RATICATE', 0.7, 18.5, 0, -1, 100, 120, 100, 120, 100, 80, 25, 500);