CREATE TABLE ANIMATURE (
	"id" INTEGER NOT NULL PRIMARY KEY,
	"height" REAL NOT NULL,
	"weight" REAL NOT NULL,
	"type" INTEGER NOT NULL,
	"speed" INTEGER NOT NULL,
	"defense" INTEGER NOT NULL,
	"agility" INTEGER NOT NULL,
	"strenght" INTEGER NOT NULL,
	"precission" INTEGER NOT NULL,
	"health" INTEGER NOT NULL,
	"evo_level" INTEGER,
	"base_exp" INTEGER  NOT NULL,
	"capture_range" INTEGER NOT NULL);

CREATE TABLE ATTACK (
	"id" INTEGER NOT NULL PRIMARY KEY,
	"type" INTEGER NOT NULL,
	"max_pp" INTEGER NOT NULL,
	"attribute" INTEGER,
	"power" INTEGER NOT NULL,
	"probability" INTEGER NOT NULL,
	"isFirst" INTEGER NOT NULL);

CREATE TABLE CAPTURABLE (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"animature" INTEGER NOT NULL REFERENCES ANIMATURE(id) ON DELETE CASCADE,
	"save" INTEGER REFERENCES SAVE(id) ON DELETE CASCADE,
	"nickname" TEXT,
	"sex" INTEGER NOT NULL,
	"status" INTEGER NOT NULL,
	"captured_time" INTEGER NOT NULL,
	"attack1" INTEGER REFERENCES ATTACK(id) ON DELETE SET NULL,
	"attack1_pp" INTEGER,
	"attack2" INTEGER REFERENCES ATTACK(id) ON DELETE SET NULL,
	"attack2_pp" INTEGER,
	"attack3" INTEGER REFERENCES ATTACK(id) ON DELETE SET NULL,
	"attack3_pp" INTEGER,
	"attack4" INTEGER REFERENCES ATTACK(id) ON DELETE SET NULL,
	"attack4_pp" INTEGER,
	"baseHealth" INTEGER NOT NULL,
	"health" INTEGER NOT NULL,
	"level" INTEGER NOT NULL,
	"cur_exp" INTEGER NOT NULL,
	"exp" INTEGER NOT NULL,
	"box" INTEGER);

CREATE TABLE ITEM (
	"id" INTEGER NOT NULL PRIMARY KEY,
	"type" INTEGER NOT NULL);

CREATE TABLE ENEMY (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"map" INTEGER NOT NULL,
	"coord_x" INTEGER NOT NULL,
	"coord_y" INTEGER NOT NULL,
	"money" INTEGER NOT NULL,
	"an1" INTEGER NOT NULL REFERENCES CAPTURABLE(id) ON DELETE SET NULL,
	"an2" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL,
	"an3" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL,
	"an4" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL,
	"an5" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL,
	"an6" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL);

CREATE TABLE USER (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"email" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"username" TEXT NOT NULL,
	"is_current" INTEGER NOT NULL,
	"remember" INTEGER NOT NULL);

CREATE TABLE SAVE (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"user" INTEGER NOT NULL REFERENCES USER(id) ON DELETE CASCADE,
	"name" TEXT NOT NULL,
	"sex" INTEGER  NOT NULL,
	"stage" INTEGER NOT NULL DEFAULT 0,
	"last_played" INTEGER NOT NULL,
	"start_date" INTEGER NOT NULL,
	"total_time" INTEGER NOT NULL,
	"steps" INTEGER DEFAULT 0,
	"an1" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL DEFAULT NULL,
	"an2" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL DEFAULT NULL,
	"an3" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL DEFAULT NULL,
	"an4" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL DEFAULT NULL,
	"an5" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL DEFAULT NULL,
	"an6" INTEGER REFERENCES CAPTURABLE(id) ON DELETE SET NULL DEFAULT NULL,
	"map" INTEGER NOT NULL,
	"coord_x" INTEGER NOT NULL,
	"coord_y" INTEGER NOT NULL,
	"neighbor" TEXT NOT NULL,
	"first_an" INTEGER NOT NULL REFERENCES ANIMATURE(id) ON DELETE SET NULL,
	"orientation" INTEGER NOT NULL,
	"last_healing_map" INTEGER DEFAULT NULL,
	"last_healing_x" INTEGER DEFAULT NULL,
	"last_healing_y" INTEGER DEFAULT NULL,
	"medals" INTEGER NOT NULL DEFAULT 0,
	"money" INTEGER NOT NULL DEFAULT 0,
	CHECK (last_healing_map IS NULL OR (last_healing_map IS NOT NULL AND last_healing_x IS NOT NULL AND last_healing_y IS NOT NULL)),
	UNIQUE (user, name));

CREATE TABLE BAG (
	"save" INTEGER NOT NULL REFERENCES SAVE(id) ON DELETE CASCADE,
	"item" INTEGER NOT NULL REFERENCES ITEM(id) ON DELETE CASCADE,
	"quantity" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (save, item));

CREATE TABLE VIEWED (
	"save" INTEGER REFERENCES SAVE(id) ON DELETE CASCADE,
	"animature" INTEGER REFERENCES ANIMATURE(id) ON DELETE CASCADE,
	PRIMARY KEY (save, animature));

CREATE TABLE ANIMATURE_ATTACKS (
	"animature" INTEGER REFERENCES ANIMATURE(id) ON DELETE CASCADE,
	"attack" INTEGER REFERENCES ATTACK(id) ON DELETE CASCADE,
	"level" INTEGER,
	PRIMARY KEY (animature, attack));

CREATE TABLE FIGHT (
	"save" INTEGER NOT NULL REFERENCES SAVE(id) ON DELETE CASCADE,
	"enemy" INTEGER NOT NULL REFERENCES ENEMY(id) ON DELETE CASCADE,
	PRIMARY KEY (save, enemy));
